server:
  port: 8002

spring:
  application:
    name: adService
  datasource:
    username: user3_2
    password: ooad2
    url: jdbc:mysql://47.52.88.176:3306/DB3_2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xmu.yida.ad.domain
  configuration:
    map-underscore-to-camel-case: true
#showSql
logging:
  level:
    com:
      example:
        mapper : debug

eureka:
  client:
    service-url:
      defaultZone: http://handsomeyida.xyz:8761/eureka
  instance:
    instance-id: adService8002-hystrix
    prefer-ip-address: true
    ip-address: 123.56.30.118

info:
  app.name: adService
  company.name: XMU
  author: LYD
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"

