server:
  port: 6666



eureka:
  client:
    service-url:
      defaultZone: http://handsomeyida.xyz:8761/eureka
  instance:
    instance-id: oomall-zuul-gatewat6666
    prefer-ip-address: true

info:
  app.name: zuulService
  company.name: XMU
  author: LYD
  build.artifactId: @project.artifactId@
  build.version: @project.version@

spring:
  application:
    name: myzuul
  datasource:
    username: ooadUser
    password: root
    url: jdbc:mysql://localhost:3306/oomal?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5 #数据库连接池的最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 5 #最大连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间

